version: '3.1'
services:
  sample:
    build:
        context: .
    image: kapil790/multi
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
        - "8025:8025"
        - "1025:1025"
       