version: '3.1'
services:
  sample:    
    image: my-registry:55000/sample:ci-25
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"" 
      