version: '3.1'
services:
  sample:    
    image:  my-registry:55000/sample:ci-3
    #ports:
     # - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
        #- "8025:8025"        
  integration:
    image: my-registry:55000/integtaion:10
    build: .